version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/modules/dynamodb"
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/modules/lambda"
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/modules/sns"
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/modules/sqs"
    schedule:
      interval: "monthly"
