framework:
  - all

skip-check:
  - CKV_AWS_26
  - CKV_AWS_27
  - CKV_AWS_28
  - CKV_AWS_50
  - CKV_AWS_116
  - CKV_AWS_119
  - CKV_AWS_117
  - CKV_AWS_158
  - CKV_AWS_173
  - CKV_AWS_272
  - CKV_AWS_338
  - CKV2_AWS_16

soft-fail: true
